FROM django:3.2.13 AS builder-image

FROM ubuntu:20.04 AS runner-image

RUN apt-get update && \
    apt-get install --no-install-recommends -y \
    python3.9 python3-venv && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder-image /opt/venv /opt/venv

ENV APP_HOME=/app
RUN mkdir ${APP_HOME}
WORKDIR ${APP_HOME}
COPY . .

# 移除\r in windows
RUN sed -i 's/\r//' start.sh && \
    chmod +x start.sh

ENTRYPOINT [ "/bin/bash" ]
CMD [ "start.sh" ]

